server:
  port: 3000

spring:
  profiles:
    active: local

---

spring:
  devtools: # 수정하면 바로 새로고침 devtools (배포할 때 제거)
    livereload:
      enabled: true
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      password:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql : true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false # 스프링 배치 자동 설정으로 인해 스프링 부트 시작시 등록되어 있는 job들이 실행되며
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    com.followproject: debug

---


spring:
  devtools: # 수정하면 바로 새로고침 devtools (배포할 때 제거)
    livereload:
      enabled: true
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: hgs3164
      jdbc-url: jdbc:mysql://localhost:3306/batch_test?logger=Slf4JLogger
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql : true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false # 스프링 배치 자동 설정으로 인해 스프링 부트 시작시 등록되어 있는 job들이 실행되며
  config:
    activate:
      on-profile: batch

logging:
  level:
    com.followproject: debug
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate : DEBUG

