insert into user(name,is_active) values('hyun',true );
insert into user(name,is_active) values('lee',true);
insert into user(name,is_active) values('kim',true);
insert into user(name,is_active) values('choi',true);
insert into post(title,content,user_id,is_active) values('title1','content1',1,true);
insert into post(title,content,user_id,is_active) values('title2','content2',1,true);
insert into post(title,content,user_id,is_active) values('title3','content3',2,true);
insert into post(title,content,user_id,is_active) values('title4','content4',2,true);
insert into post(title,content,user_id,is_active) values('title5','content5',2,true);
insert into post(title,content,user_id,is_active) values('title6','content6',3,true);
insert into post(title,content,user_id,is_active) values('title7','content7',3,true);
insert into post(title,content,user_id,is_active) values('title8','content8',3,true);
insert into post(title,content,user_id,is_active) values('title9','content9',3,true);
insert into post(title,content,user_id,is_active) values('title10','content10',4,true);
insert into post(title,content,user_id,is_active) values('title11','content11',4,true);
insert into post(title,content,user_id,is_active) values('title12','content12',4,true);